---
abstract: 'Create barcode image with GD'
author:
  - 'Kawai Takanori <GCD00051@nifty.ne.jp>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0.000060'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GD-Barcode
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/mbeijen/GD-Barcode/issues
  repository: https://github.com/mbeijen/GD-Barcode
version: '2.00'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
